export interface Question {
  id: number;
  q: string;
  options: string[];
  answer: number;
}

export interface ExamCategory {
  id: string;
  title: string;
  description: string;
  durationMin: number;
  accent: string;
  icon: string;
  marksPerQuestion: number;
  negativeMarkFraction: number;
  questions: Question[];
}

const placeholder = (topic: string): Question[] =>
  Array.from({ length: 5 }).map((_, i) => ({
    id: i + 1,
    q: `[${topic}] Sample question ${i + 1} - replace with real question.`,
    options: ["Option A", "Option B", "Option C", "Option D"],
    answer: 0,
  }));

const Q = (id: number, q: string, options: string[], answer: number): Question => ({ id, q, options, answer });

const aptitudeQuestions: Question[] = [
  Q(1, "In an exhaustive macroeconomic analysis of post-industrial agrarian supply chains, researchers observed a profound operational paradox: while the systemic implementation of high-frequency automated harvesting sub-routines universally escalated the absolute raw material yield across all tested demographics, the aggregate profitability metrics of the adopting cooperatives paradoxically demonstrated a statistically significant negative correlation over a fiscal quadriennium. Further forensic market auditing revealed that the artificially accelerated yield vectors induced a hyper-localized market saturation, thereby completely destabilizing the equilibrium of the localized price-elasticity curve. Based strictly on the empirical data and causal relationships explicitly articulated in this synopsis, which of the following extrapolations represents the most logically rigorous deduction?",
    ["The deployment of automated harvesting sub-routines is inherently detrimental to the long-term ecological sustainability of agrarian sectors.", "The aggregate financial deficit incurred by the cooperatives is directly and exclusively attributable to the exorbitant mechanical maintenance costs of the automated systems.", "A quantifiable escalation in raw material output does not unconditionally guarantee a corresponding proportional increase in the aggregate profitability of the producing entity.", "Hyper-localized market saturation is an inevitable, unavoidable consequence of all technological modernization efforts within the agricultural industry."], 2),
  Q(2, "Inside a large-scale enterprise data center, two parallel data-ingestion algorithms are benchmarked against the same one-petabyte sensor archive. Algorithm Alpha, operating in complete isolation on its dedicated cluster, requires exactly 24 continuous hours to process the full petabyte. Algorithm Beta, on an identically provisioned cluster, requires 36 continuous hours for the same workload. The operations team now decides to execute both algorithms concurrently, on disjoint hardware, against shared logical partitions of the very same petabyte. After exactly 8 wall-clock hours of concurrent execution, what fraction of the one-petabyte dataset still remains unprocessed?",
    ["5/9", "4/9", "7/18", "11/18"], 1),
  Q(3, "A regulatory compliance officer is auditing a designated consumption zone governed by a strict statutory mandate: 'Any biological entity engaging in the ingestion of ethanol-based beverages must possess a verified chronological age strictly exceeding 18 solar years.' The officer observes four entities: Entity Alpha is actively consuming an ethanol-based beverage; Entity Beta is consuming a non-alcoholic botanical extract; Entity Gamma's official identification verifies a chronological age of precisely 16 solar years; and Entity Delta possesses documentation proving an age of 22 solar years. To rigorously prove that no statutory violations are occurring, the officer must execute a state-verification procedure on which precise combination of entities?",
    ["Only Entity Alpha and Entity Gamma", "Only Entity Alpha", "Entity Alpha, Beta, Gamma, and Delta", "Only Entity Alpha, Gamma, and Delta"], 0),
  Q(4, "An applied mathematics researcher is studying the algebraic behaviour of a continuous scalar variable x in the real numbers that exactly satisfies the quadratic identity x^2 + x - 1 = 0. Working purely from this relation and without resorting to numerical approximation or a calculator, the researcher must determine the exact closed-form numerical evaluation of the higher-order symmetric expression x^4 + 1/x^4. Which of the following values is the precise result of that evaluation?",
    ["1", "5", "7", "9"], 2),
  Q(5, "During a high-altitude scientific expedition, five researchers labelled P, Q, R, S and T must arrange their sleeping bags in a strictly linear adjacent sequence inside a narrow capsule tent. The protocol requires that P, Q and T must all be placed in positions that are strictly non-adjacent to R, and additionally that neither P nor S may occupy any position immediately to the left or to the right of Q. Given that the arrangement must satisfy every one of these adjacency restrictions simultaneously, which of the following depicts the exact left-to-right positional sequence of the five researchers?",
    ["R, S, P, T, Q", "Q, S, P, T, R", "R, P, S, T, Q", "P, S, R, T, Q"], 0),
  Q(6, "Inside a chemical processing plant, a primary containment vessel initially holds exactly 40 cubic meters of brine that has been homogenised to a 15% volumetric salinity concentration. Owing to a prolonged thermal exposure cycle in which only the water solvent vaporises while the dissolved salt remains entirely in suspension, exactly 16 cubic meters of the H2O solvent is lost to evaporation. After the evaporation phase concludes, what is the updated percentage salinity of the now concentrated solution that remains inside the vessel?",
    ["20%", "22.5%", "25%", "31.5%"], 2),
  Q(7, "An algorithmic quantitative trading protocol recently liquidated a digital asset and, in doing so, realised an 18% financial deficit relative to its original fiat acquisition cost. Post-trade analysis of the order book reveals that had the very same asset been liquidated at a price point exactly 680 INR higher than the actual execution price, the same transaction would have instead yielded a 16% fiscal surplus over that same acquisition cost. Working strictly from these two profit-and-loss scenarios, what was the absolute initial fiat acquisition cost of the asset?",
    ["1,800 INR", "2,000 INR", "2,500 INR", "3,400 INR"], 1),
  Q(8, "Two unknown real numbers u and v are constrained by a system of symmetric algebraic identities: their arithmetic sum u + v equals 7, and their product u*v equals 10. Without explicitly solving the underlying quadratic for the individual values of u and v, and using only standard symmetric polynomial identities, determine the exact value of the cubic expression u^3 + v^3 that these two numbers must jointly satisfy.",
    ["125", "133", "217", "343"], 1),
  Q(9, "A perfectly uniform solid cube is first painted on every one of its six exterior faces and then partitioned by straight cuts parallel to its faces into exactly 27 smaller isometric sub-cubes of equal dimensions. When the resulting collection of sub-cubes is separated and examined, some sub-cubes carry paint on three faces, some on two, some on one, and some carry no paint at all. Exactly how many of these 27 sub-cubes will be found to have paint on precisely two of their faces?",
    ["4", "8", "12", "24"], 2),
  Q(10, "Despite the investigator's assertion that the new framework would establish a transparent, universally applicable, and ________ paradigm for predicting anomalous particle trajectories, the publication was so densely layered with contradictory axioms and recursive logic loops that it only served to ________ the very phenomena it was engineered to clarify. Choose the pair of words that best preserves the intended contrast of the sentence.",
    ["unambiguous ... obfuscate", "convoluted ... elucidate", "irrefutable ... synthesize", "esoteric ... propagate"], 0),
  Q(11, "A systems engineer must arrange a total of twelve items in a single straight line on a server rack. Five of the items are tightly coupled software modules labelled M1, M2, M3, M4 and M5, which must always remain consecutive and must additionally appear strictly in the order M1, M2, M3, M4, M5 wherever the block is placed. The remaining seven items are seven distinguishable hardware chassis that may appear in any order. Considering both arrangements together, how many unique linear configurations of the twelve items are possible?",
    ["5,040", "40,320", "3,628,800", "39,916,800"], 1),
  Q(12, "Two unknown real numbers x and y satisfy a pair of simultaneous conditions extracted from a logistics planning problem: their sum is exactly 32, and the absolute value of their difference is exactly 18. Without losing generality regarding which of the two numbers is larger, and using only elementary identities involving sums and differences, compute the exact value of the product xy that these two numbers must jointly satisfy.",
    ["175", "225", "400", "576"], 0),
  Q(13, "While reviewing a chained exponential relation that appears in a cryptography exercise, a candidate encounters the following identity in a real variable y: 5 raised to the power (2y - 1) is exactly equal to 3125. Using this identity alone, without using a calculator and without numerically approximating any logarithms, determine the exact integer value of the related exponential expression 4 raised to the power (y + 2).",
    ["256", "1024", "4096", "16384"], 1),
  Q(14, "A municipal census report records that the current population of a small town stands at exactly 1,102,500 individuals, and a footnote clarifies that this figure was reached after two consecutive years of population growth compounded annually at a steady rate of 5% per year. Assuming that the compounding is strictly annual and that no migration adjustments are applied, what was the baseline population of the town exactly 24 months prior to the current measurement?",
    ["1,000,000", "1,025,000", "1,050,000", "995,000"], 0),
  Q(15, "Two high-speed locomotives depart from the same origin station at exactly 07:00 hours, travelling along perfectly straight tracks in directly opposite directions: the first heads due North at a constant 80 km/h while the second heads due South at a constant 100 km/h. Neither train decelerates, halts at any intermediate station, or reverses direction at any point during the journey. At what clock time will the straight-line separation between the two trains first reach exactly 540 km?",
    ["09:00", "10:00", "11:00", "11:30"], 1),
  Q(16, "A clinical research team enrolls a cohort of exactly 250 volunteers in a controlled drug-interaction study. Of these volunteers, 130 individuals display a reaction to compound X, 110 individuals display a reaction to compound Y, and exactly 40 individuals are observed to react to both compounds simultaneously. Assuming every volunteer is observed for both compounds and that the only possible classifications are reaction to X, reaction to Y, both, or neither, how many of the 250 volunteers turn out to be asymptomatic to both compounds?",
    ["30", "50", "70", "90"], 1),
  Q(17, "A chemical retailer prepares two industrial solutions: solution Alpha contains active ingredient and solvent in the ratio 1:3, and solution Beta contains active ingredient and solvent in the ratio 1:4. The retailer blends Alpha and Beta in the volumetric ratio 2:3 to produce a mixture. Alpha alone, when sold at its per-litre price, yields the retailer a 20% profit. The retailer now sells the blended mixture at the very same per-litre price as Alpha but pays nothing for the solvent. What is the overall profit or loss percentage realised on the mixture?",
    ["25.55% profit", "36.36% profit", "18.18% deficit", "42.00% profit"], 1),
  Q(18, "A reconnaissance UAV takes off from a fixed launch coordinate and first flies in a perfectly straight line due North for exactly 24 km without any altitude change. Upon reaching the end of that leg the UAV executes a sharp 90-degree yaw to its starboard side, so that it now points due East, and immediately proceeds straight in that new heading for an additional 7 km before halting. Treating the ground track as a flat plane, what is the straight-line displacement magnitude from the launch point, and what is the approximate compass heading?",
    ["25 km, NE", "31 km, NE", "25 km, NW", "31 km, NW"], 0),
  Q(19, "A retail investor deposits a principal amount of exactly 12,000 INR into a fixed-deposit instrument that pays 5% per annum, compounded strictly once per year, and leaves the deposit completely untouched for a continuous period of three full years with no additional contributions or withdrawals. At the end of the third year, the bank credits the matured value back to the investor's account. What is the total interest accumulated by the deposit over the entire three-year compounding window?",
    ["1,800.00", "1,891.50", "1,925.25", "2,050.00"], 1),
  Q(20, "A quality-assurance technician is testing microprocessors drawn from a sealed shipment that contains exactly 20 units, of which 8 are known to be defective and the remaining 12 are known to be fully functional. The technician draws 3 units one after another at random, strictly without replacement between draws. Assuming all draws are uniformly random over the units that remain at each stage, what is the exact probability that all 3 of the drawn microprocessors turn out to be fully functional?",
    ["11/57", "33/95", "27/125", "12/57"], 0),
  Q(21, "A 200-metre-long maglev train travelling at a uniform cruising speed of exactly 144 km/h enters one mouth of a perfectly straight, level tunnel that is itself exactly 600 metres long, with no acceleration or deceleration anywhere inside the tunnel. The relevant clock begins the instant the leading nose of the train crosses the entrance of the tunnel and stops the instant the trailing end of the train clears the far exit. How many seconds elapse between those two events?",
    ["15", "20", "22.5", "25"], 1),
  Q(22, "An optical engineer is fabricating perfectly circular silicon wafers and notes that the radius of a particular wafer design has just been increased by exactly 15% relative to the previously approved baseline design, while every other geometric property remains untouched. Assuming the wafer remains a perfect circle and that the area scales as the square of the radius, what is the corresponding percentage increase in the surface area of the redesigned wafer compared to the original?",
    ["15.00%", "30.00%", "32.25%", "35.50%"], 2),
  Q(23, "A senior data scientist remarks on a newly captured set of high-frequency anomaly traces by saying that the fluctuations defy every known framework of analysis available in the literature and that it is simply impossible to rationalise, interpret, or even articulate them within the existing vocabulary of the field. Which single word most precisely captures the quality the scientist is describing in that statement?",
    ["Incomprehensible", "Indelible", "Inextricable", "Infallible"], 0),
  Q(24, "Despite a sustained media campaign of baseless allegations and politically motivated character attacks aimed squarely at the senior magistrate over many consecutive months, neither the bar council nor the general public observed any substantive change in the magistrate's professional standing, and her reputation proved completely ________. Choose the word that best completes the sentence in keeping with its overall meaning.",
    ["undiminished", "resolved", "illegal", "uncertain"], 0),
  Q(25, "A control-room operator glances at a perfectly standard analogue 12-hour wall clock at precisely 08:30 hours and wishes to determine the acute angle, measured in degrees, formed between the hour hand and the minute hand of the clock at exactly that instant. Assuming both hands move continuously and uniformly at their conventional rates, what is the exact acute angle between the two hands at this moment?",
    ["60°", "75°", "85°", "90°"], 1),
  Q(26, "Two unknown real numbers x and y arising in an algebraic word problem are jointly constrained so that their arithmetic sum x + y equals exactly 5 and their product x*y equals exactly 6. Without first explicitly solving the underlying quadratic for the individual values of x and y, and relying only on standard symmetric polynomial identities, compute the exact value of the cubic expression x^3 + y^3 implied by these constraints.",
    ["35", "91", "125", "215"], 0),
  Q(27, "A government policy paper opens with the statement: 'Ban all diesel vehicles older than 10 years in order to improve urban air quality.' Two readers extract the following candidate assumptions from this single sentence: (I) Older diesel vehicles contribute significantly to urban air pollution, and (II) Banning older diesel vehicles is the only available method of improving urban air quality. Which of these assumptions is genuinely implicit in the given statement?",
    ["Only I", "Only II", "Both I and II", "Neither I nor II"], 0),
  Q(28, "An opaque cloth bag contains exactly 5 indistinguishable red balls and 7 indistinguishable blue balls, all of identical size and weight, and a player draws two balls one after another at random and strictly without replacement between draws. Assuming the draws are uniformly random over the balls that remain in the bag at each stage, what is the exact probability that both of the drawn balls turn out to be red?",
    ["5/33", "5/12", "25/144", "10/33"], 0),
  Q(29, "A perfectly rectangular sheet of paper is first folded exactly in half along its horizontal mid-line and then folded again exactly in half along its vertical mid-line, so that the original sheet now sits as four overlapping layers of equal area. A single perfectly circular hole is then punched cleanly through all four overlapping layers simultaneously at a point that is not on any fold line. How many distinct holes will be visible when the paper is fully unfolded?",
    ["1", "2", "4", "8"], 2),
  Q(30, "A geometry student is investigating how the area of a perfect circle responds to changes in its radius and observes that the radius of a particular reference circle has just been increased by exactly 20% over its original value, while the circle remains perfectly circular. Using only the standard area formula A = πr^2 and treating π as a constant, what is the exact percentage increase in the area of the new circle compared to the area of the original?",
    ["20%", "40%", "44%", "400%"], 2),
];

// 20 Pro-Level System Design & Architecture MCQs.
const systemQuestions: Question[] = [
  Q(1, "In an HTTP/2 architecture, multiple client requests are multiplexed over a single TCP connection to an Express API Gateway. If a single packet containing a partial payload for Request A is lost in transit, what happens to Request B, which is fully received and queued behind it?",
    ["Request B is processed immediately because HTTP/2 streams are independent at the application layer.", "Request B is blocked and cannot be processed until the missing packet for Request A is retransmitted and acknowledged, due to TCP's strict ordered delivery.", "The TCP connection automatically falls back to HTTP/1.1 to process Request B.", "The API Gateway drops both requests and forces the client to initiate a new TLS handshake."], 1),
  Q(2, "You are designing a high-throughput time-series database. You choose a Log-Structured Merge (LSM) Tree over a traditional B-Tree. Which of the following is a primary trade-off of using an LSM-Tree?",
    ["LSM-Trees suffer from extreme Write Amplification, burning out SSDs much faster than B-Trees.", "LSM-Trees provide faster read performance but slower write performance compared to B-Trees.", "LSM-Trees require continuous background \"compaction\" processes that can cause periodic latency spikes during read operations.", "LSM-Trees cannot support range queries or sequential scans."], 2),
  Q(3, "A high-frequency trading platform requires absolute minimum latency. The load balancer does not need to inspect HTTP headers, cookie data, or URL paths; it only needs to distribute traffic based on IP and Port. Which load balancing strategy should be implemented?",
    ["Layer 7 HTTP Reverse Proxy", "Layer 4 Transport Level Load Balancing", "Application-Level Anycast", "DNS Round Robin with low TTL"], 1),
  Q(4, "The CAP theorem states you must choose between Consistency and Availability during a Partition (P). The PACELC theorem extends this. According to PACELC, what trade-off must a distributed database (like Cassandra or DynamoDB) make during normal operation when there is Else (E) no network partition?",
    ["Latency (L) versus Consistency (C)", "Availability (A) versus Durability (D)", "Partition Tolerance (P) versus Latency (L)", "Consistency (C) versus Partition Tolerance (P)"], 0),
  Q(5, "You implement the Command Query Responsibility Segregation (CQRS) pattern in a microservices architecture. The \"Command\" database is a heavily normalized PostgreSQL instance, and the \"Query\" database is a denormalized ElasticSearch index. What is the most significant architectural challenge introduced by this pattern?",
    ["The system can no longer handle concurrent writes.", "You must handle Eventual Consistency between the Command and Query databases, meaning users might read stale data immediately after a write.", "ElasticSearch cannot be horizontally scaled if it is used exclusively for queries.", "The API Gateway must execute Two-Phase Commits (2PC) across both databases for every read request."], 1),
  Q(6, "Your Express application consumes events from an Apache Kafka topic with 10 partitions. You scale your Node.js consumer microservice to 12 instances within the same Consumer Group. What happens to the event processing?",
    ["All 12 instances will process messages concurrently, increasing throughput by 20%.", "10 instances will process messages (one partition each), and 2 instances will sit completely idle.", "The Kafka broker will dynamically split two partitions to ensure all 12 instances receive data.", "A Split-Brain scenario occurs, causing duplicate message processing across all instances."], 1),
  Q(7, "You are replacing internal JSON-over-HTTP REST APIs with gRPC between backend microservices. Which of the following is a fundamental difference that provides gRPC its massive performance boost?",
    ["gRPC uses UDP instead of TCP, eliminating handshake latency.", "gRPC relies on Protocol Buffers (Protobuf), which transmits data as highly compressed, strongly-typed binary rather than human-readable text.", "gRPC automatically implements the Circuit Breaker pattern at the network layer.", "gRPC maintains stateful connections, eliminating the need for a database."], 1),
  Q(8, "In a distributed SQL database, a Two-Phase Commit (2PC) is used to guarantee atomicity across multiple nodes. The Coordinator node sends a \"Prepare\" message to all Participant nodes, and they all reply \"Yes.\" Before the Coordinator can send the \"Commit\" message, the Coordinator node crashes and goes offline. What state are the Participant nodes in?",
    ["They automatically abort and rollback the transaction after a 5-second timeout.", "They are blocked and must hold their database locks indefinitely until the Coordinator recovers or an administrator intervenes.", "They elect a new Coordinator from among themselves and immediately commit.", "They silently drop the transaction and accept new writes."], 1),
  Q(9, "A highly complex, cached API response expires. Suddenly, 10,000 concurrent client requests hit the cache, find it empty (Cache Miss), and all 10,000 requests simultaneously query the backend database, crashing it. Which mitigation strategy actively prevents this without serving stale data indefinitely?",
    ["Increasing the cache TTL to 30 days.", "Probabilistic Early Expiration (Cache-Busting) or Mutex Locks (Request Coalescing).", "Implementing a Least Recently Used (LRU) eviction policy.", "Switching from Memcached to Redis."], 1),
  Q(10, "A sports application features a live scoreboard. The server pushes updates to the client every 500ms. The client never sends any data back to the server other than the initial connection request. Why might Server-Sent Events (SSE) be architecturally superior to WebSockets in this specific scenario?",
    ["SSE is bidirectional, whereas WebSockets are strictly unidirectional.", "SSE runs over standard HTTP/1.1 or HTTP/2, natively supporting multiplexing, standard firewalls, and built-in automatic reconnections without custom transport layers.", "WebSockets cannot transmit binary data, making them unsuitable for live scores.", "SSE utilizes UDP, making it immune to Head-of-Line blocking."], 1),
  Q(11, "You are migrating a massive legacy monolithic application to a modern microservices architecture. Instead of a \"Big Bang\" rewrite, you implement the Strangler Fig pattern. How does this pattern operate at the system level?",
    ["A proxy (API Gateway) is placed in front of the monolith. As new microservices are built, the proxy gradually routes specific URL paths away from the monolith to the new services until the monolith can be safely decommissioned.", "The legacy database is replicated to a cloud provider, and the monolith is forced to read from the replica.", "The monolith's codebase is automatically transpiled from older languages (like Java) into Node.js using an LLM.", "Traffic is artificially restricted (throttled) to the monolith to force users onto the new system."], 0),
  Q(12, "A system uses a relational database with a Repeatable Read isolation level. Transaction A queries SELECT * FROM Orders WHERE status = 'PENDING' and gets 5 results. Transaction B simultaneously inserts a new order with a 'PENDING' status and commits. Transaction A runs the exact same query again. Under standard Repeatable Read (without Next-Key locking), what anomaly occurs?",
    ["Dirty Read: Transaction A sees uncommitted data.", "Non-Repeatable Read: An existing row Transaction A was viewing changes its values.", "Phantom Read: Transaction A suddenly sees 6 results instead of 5, as a new row matches the range condition.", "Write Skew: Transaction A overwrites Transaction B's data."], 2),
  Q(13, "A MongoDB cluster consists of 2 nodes across 2 data centers (DC1 and DC2) to ensure geographic redundancy. The network link between the data centers goes down. Both nodes assume the other is dead and promote themselves to Primary, accepting writes. When the network is restored, data is hopelessly corrupted. How is this \"Split-Brain\" prevented in modern distributed systems?",
    ["By implementing a strict Last-Write-Wins (LWW) conflict resolution algorithm.", "By ensuring the cluster always has an odd number of voting nodes (e.g., 3) and requiring a strict majority (Quorum) to elect a Primary or accept writes.", "By configuring both nodes to automatically shut down if ping times exceed 500ms.", "By manually pausing the database during network outages."], 1),
  Q(14, "You are designing an architecture for a video streaming platform like Netflix. You need to store petabytes of immutable, massive video files that will be served directly to Edge CDNs. Which storage architecture is appropriate?",
    ["Block Storage (e.g., AWS EBS) because it allows byte-level modification of the video files.", "Object Storage (e.g., AWS S3) because it scales infinitely, stores data as immutable objects with rich metadata, and provides native HTTP access.", "Relational Database BLOBs because it ensures strict ACID compliance for video playback.", "File Storage (e.g., AWS EFS) because it allows thousands of servers to mount the same OS directory natively."], 1),
  Q(15, "An asynchronous worker process consumes messages from a RabbitMQ queue to send confirmation emails. Due to a bug in the email formatting code, a specific message repeatedly crashes the worker. The broker continuously requeues the message, crashing the worker in an infinite loop (a \"Poison Pill\"). How is this resolved at the system level?",
    ["Configure the worker to silently acknowledge (ACK) and delete all failed messages.", "Configure the broker's retry policy to route the message to a Dead Letter Queue (DLQ) after a threshold of failed attempts, allowing the worker to process the rest of the queue.", "Increase the worker's RAM allocation.", "Switch from RabbitMQ to a purely synchronous HTTP REST architecture."], 1),
  Q(16, "You use stateless JSON Web Tokens (JWT) for API authentication. A user's account is compromised, and you need to instantly invalidate their active 60-minute JWT. Because JWTs are stateless and validated via cryptography on the API server, how do you revoke it before expiration without creating a database bottleneck?",
    ["Change the server's master signing secret, which instantly invalidates all JWTs for all users globally.", "Maintain a high-speed, centralized \"Deny List\" of revoked Token IDs (jti) in an in-memory datastore like Redis, checked by the Gateway on every request.", "Send an HTTP DELETE request to the client's browser to wipe their local storage.", "You cannot revoke a stateless JWT; you must wait the full 60 minutes for it to expire."], 1),
  Q(17, "You have 4 Redis cache servers. You route keys based on hash(key) % 4. Server #4 crashes. The algorithm changes to hash(key) % 3. Suddenly, 75% of your cached keys route to the wrong servers, causing a massive cache miss. Which concept solves this by mapping nodes and keys to a virtual ring, ensuring only a small fraction of keys are remapped when a node dies?",
    ["Linear Probing", "Round-Robin Hashing", "Consistent Hashing", "Cryptographic Hashing (SHA-256)"], 2),
  Q(18, "An API Gateway utilizes a Circuit Breaker pattern to protect a failing downstream microservice. The microservice recovers and comes back online. The Circuit Breaker transitions from the \"Open\" (failing fast) state to a testing state where it allows a limited number of requests through to verify recovery. What is this state called?",
    ["Closed", "Half-Open", "Throttled", "Dead-Letter"], 1),
  Q(19, "An API rate limiter uses the Token Bucket algorithm. The bucket holds a maximum of 10 tokens and is refilled at a rate of 1 token per second. A user has not made a request in 5 minutes. The user suddenly sends 15 concurrent requests. What happens?",
    ["10 requests are processed immediately (the burst), and 5 requests are rejected (HTTP 429).", "All 15 requests are processed immediately because the user has built up 300 seconds of unused capacity.", "The requests are processed strictly at 1 request per second for 15 seconds.", "All 15 requests are rejected because they exceed the 1-per-second refill rate."], 0),
  Q(20, "In a high-contention ticketing system (like buying concert tickets), thousands of users are trying to buy the same seat simultaneously. If you use Optimistic Concurrency Control (OCC) using version numbers, what is the primary system drawback compared to P